### ISSUE TITLE
Reusable components

### ISSUE THREAD

**Issue by hipertracker** [optimizely/nuclear-js#100]
Is nuclear-js using singletons? I took https://github.com/optimizely/nuclear-js/tree/rest-api-example/examples/flux-chat, added mock-data2.js and mounted it twice to, a different part of the web page. 

https://gist.github.com/hipertracker/6aa9ef3dd513471f72c4

It looks like those components are not isolated and share some state. :( 

How to reuse the same component? (The only difference would be data passed to it)

**Comment by hipertracker** [comment]
It looks to be [more common problem](https://medium.com/front-end-development-2/multiple-components-in-flux-acd73d8fceef)... The Facebook's way is to use the [component containers](https://youtu.be/KYzlpRvWZ6c?t=22m51s) which talk to the stores. Some others uses store factories. 

What would be the best way for NuclearJS? I just want to create a nuclear-js module and use it in few places on the page. All of them should be aggressive decoupled and know nothing about the others.

**Comment by rattrayalex** [comment]
It's not clear from your example how you're using `reactor`. I personally don't know the internals well enough to provide an answer, but I would assume it *should* be unique-per-reactor. Otherwise, I would agree it's probably something that should be fixed; an application should be able to have multiple non-conflicting reactors IMO.

**Comment by hipertracker** [comment]
I explained it in the beginning. I just took https://github.com/optimizely/nuclear-js/tree/rest-api-example/examples/flux-chat  as it is, and [have modified 2 files](https://gist.github.com/hipertracker/6aa9ef3dd513471f72c4). 

The goal is to use the same component at least twice on the same page without sharing the same internal  *local* state. E.g. it could be a complex datatable component (with sorting, filtering etc) which would be used twice on the same page. Every instance of it would be populated with a different data set. I'd like to sort and filter each of them without having a conflict. 

I am not sure where nuclear-js is keeping the local state of the component. In my example that state is apparently shared among both instances of the component... Is the reactor the place which keeps the local state of the component? If it is, I would need a second reactor assigned to the same component, right? Is there any example of how it could work?

**Comment by hipertracker** [comment]
After digging more into [flux-chat](https://github.com/optimizely/nuclear-js/tree/rest-api-example/examples/flux-chat) example I found out that the shared part is because is in modules/chat/* files not components/* section. If I understand it correctly, the component do not have the state at all. It is all controlled by the nuclear-js module. The **internal subcomponents** of `<ChatApp/>`: `<ThreadSection/>` and `<MessageSection/>` are using the same `Chat` module. So even if I add another `<ChatApp/>' it's subcomponents will still use the same module, and share the same data. So I cannot get an independent, isolated instances of `<ChatApp/>`. 

The question is: how to make nuclear-js module working independent per the component. Maybe , instead of using `require` I would need a factory pattern here? Any better idea?

**Comment by jordangarcia** [comment]
Hi @hipertracker 

The current examples are essentially using singletons since they dont deal with isomorphic rendering.

A way to get around this would be to have the modules export an object of stores instead of registering them directly on a specific reactor instance.  

Lastly for actions they could be passed a reactor instance as the first argument.

This is a sort of temporary solution as we investigate what NuclearJS isomorphic story actually looks like in the upcoming 1.1 release

I would be happy to take design suggestions or contributions with this.  If you are interested feel free to get in touch with me directly at jordan@optimizely.com

**Comment by rattrayalex** [comment]
Thoughts on this as an idea? (treat as pseudocode, haven't ran it)

https://gist.github.com/rattrayalex/cb5551618df6d77417c3

It introduces a dependency on React, so might be better as a third party lib...

**Comment by Sinewyk** [comment]
You should be able to manage what you want with the now released https://www.npmjs.com/package/nuclear-js-react-addons.

What you would want is create 2 reactor, register your stores on them, and use provideReactor to give it to your 2 "different" chat apps. You should have no problem doing that.

**Comment by bhamodi** [comment]
@Sinewyk - is this issue considered resolved now?

**Comment by Sinewyk** [comment]
Yes.

**Comment by bhamodi** [comment]
Sweet, thanks for your help @Sinewyk!
